# Generated by Django 3.0.8 on 2020-07-29 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200728_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Breed', 'verbose_name_plural': 'Breeds'},
        ),
        migrations.AlterModelOptions(
            name='subbreed',
            options={'verbose_name': 'Sub-Breed', 'verbose_name_plural': 'Sub-Breeds'},
        ),
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.AddField(
            model_name='dog',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subbreed',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Breed'),
        ),
    ]
