# Generated by Django 3.0.8 on 2020-07-29 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200729_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sub_breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customer.SubBreed', verbose_name='Sub-Breed'),
            preserve_default=False,
        ),
    ]
