# Generated by Django 3.0.8 on 2020-07-29 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_dog_sub_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='sub_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.SubBreed', verbose_name='Sub-Breed'),
        ),
    ]
