# Generated by Django 3.0.8 on 2020-07-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200729_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(upload_to='dogs/'),
        ),
    ]
