# Generated by Django 3.0.8 on 2020-07-29 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_auto_20200729_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Check-in')),
                ('check_out', models.DateTimeField(verbose_name='Check-out')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Dog')),
            ],
        ),
    ]
